use crate::backend::spec::Operation;

pub fn operation_kind(op: &Operation) -> &'static str {
    match op {
        Operation::Constant(_) => "constant",
        Operation::ElementwiseUnary(_) => "elementwise_unary",
        Operation::ElementwiseBinary(_) => "elementwise_binary",
        Operation::DotGeneral(_) => "dot_general",
        Operation::Reduce(_) => "reduce",
        Operation::ArgMax(_) => "argmax",
        Operation::Compare(_) => "compare",
        Operation::Select => "select",
        Operation::Cast(_) => "cast",
        Operation::StopGradient => "stop_gradient",
        Operation::Reshape(_) => "reshape",
        Operation::Transpose(_) => "transpose",
        Operation::BroadcastTo(_) => "broadcast_to",
        Operation::Slice(_) => "slice",
        Operation::Concat(_) => "concat",
        Operation::Pad(_) => "pad",
        Operation::Tile(_) => "tile",
        Operation::Iota(_) => "iota",
        Operation::Take => "take",
        Operation::Gather(_) => "gather",
        Operation::ScatterAdd(_) => "scatter_add",
        Operation::ScatterReduce(_) => "scatter_reduce",
        Operation::DynamicSlice(_) => "dynamic_slice",
        Operation::DynamicUpdateSlice(_) => "dynamic_update_slice",
        Operation::Cond(_) => "cond",
        Operation::While(_) => "while",
        Operation::Scan(_) => "scan",
        Operation::ExtractPatches(_) => "extract_patches",
        Operation::ReduceWindow(_) => "reduce_window",
        Operation::RngUniform(_) => "rng_uniform",
        Operation::RngNormal(_) => "rng_normal",
        Operation::TopK(_) => "top_k",
        Operation::SegmentReduce(_) => "segment_reduce",
        Operation::Quantize(_) => "quantize",
        Operation::Dequantize(_) => "dequantize",
        Operation::Requantize(_) => "requantize",
        Operation::CustomCall(_) => "custom_call",
    }
}
